### PR TITLE
Feature/basic auth

### PR DESCRIPTION
**Pull request by pierocampa**
Added support for Basic Authentication (BA) + Bearer token (JWT-based).

### Added
- new [`org.openeo.spring.security`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/security) package where to store the configurations of all auth and security related mechanisms;
- configuration of BA auth mechanism ([`BasicSecurityConfig`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/security/BasicSecurityConfig.java)), and its customization bean [`BAuthEntrypoint`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/components/BAuthEntrypoint.java);
- JWT tokens parsing, generation as a service, and related filters for the Spring Security filters chains (see [`org.openeo.spring.bearer`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/bearer) package);
- configuration of CORS response headers and pre-flight requests management in [`CorsConfig`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/security/CorsConfig.java);
- runtime exceptions catcher and resolver via [`FilterChainExceptionHandler`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/components/FilterChainExceptionHandler.java) and [`ExceptionTranslator`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/components/ExceptionTranslator.java);
- custom error attributes to convert auth errors into openEO API errors ([`ErrorAttributes`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/components/ErrorAttributes.java));
- 2 more "switch" properties in the `application.properties` file, to control the enablement of auth mechanisms:
  - **`spring.security.enable-basic`**`= [true|false]`
  - **`spring.security.enable-keycloak`**`= [true|false]`
- refactored out Keycloak-related properties from the main `application.properties` to the [`keycloak.properties`](../blob/feature/basic-auth/src/test/resources/keycloak-test.properties) file;
- added a new properties file for the configuration of the JWT tokens for BA: [`jwt.properties`](../blob/feature/basic-auth/src/main/resources/jwt.properties);
- Add favicon in [*src/main/resources/static/*](../blob/feature/basic-auth/src/main/resources/static) folder;
- integration and unit tests for all above mentioned functionalities (see [*./src/test/java/org/openeo/spring*](../blob/feature/basic-auth/src/test/java/org/openeo/spring/)): `mvn test` from the project's root shall pass all of them.

### Upgraded
- *Spring Boot* from 2.5.1 to 2.6.1, which means an upgrade of *Spring Framework* from 5.3.8 to 5.3.13. and of *Spring Security* from 5.5.0 to 5.6.0:
   - security components now shall not extend `WebSecurityConfigurerAdapter` but rather use `@EnableWebSecurity` annotations/beans: see [Spring blog](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter).
   - upgrade `springdoc-openapi-ui` from 1.4.6 to 1.5.13 to fix path pattern matching issue ([link](https://spring.io/blog/2020/06/30/url-matching-with-pathpattern-in-spring-mvc))
- configuration of Keycloak with new *Spring Boot* classes instead of the deprecated `KeycloakWebSecurityConfigurerAdapter`. Newly added Maven dependencies for this:
  - [`spring-boot-starter-oauth2-resource-server`](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-oauth2-resource-server)
  - [`spring-boot-starter-oauth2-client`](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-oauth2-client)
- Tests to use JUnit5 (instead of old Junit4). 

### Deprecated
- old Keycloak configuration components were disabled, deprecated and moved to the [`org.openeo.spring.keycloak.legacy`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/keycloak/legacy) package;
- Keycloak-related [`AuthzService`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/keycloak/legacy/AuthzService.java) has been disabled (I am also unsure about its use).

### Not supported

- simultaneous enablement of BA and Keycloak authentication mechanisms; implementation-wise, it should be (see nested classes of [`GlobalSecurityConfig`](../blob/feature/basic-auth/src/main/java/org/openeo/spring/security/GlobalSecurityConfig.java)), but there are a few tests that do not pass in the [`TestBasicAuthentication_OIDCEnabled`](../blob/feature/basic-auth/src/test/java/org/openeo/spring/security/TestBasicAuthentication_OIDCEnabled.java) test case: will create an issue for this.

----

The implementation has followed the [openeo API v1.1.0](https://api.openeo.org/1.1.0).

### CODE REVIEW

**Comment by clausmichele** [comment]
@pierocampa since this includes many changes, I think the best would be to set up the spring-driver in a new Ubuntu 22 VM and test the functionality with some real interactions.

**Comment by clausmichele** [comment]
@pierocampa some things that need to be fixed before moving on:
1. The /processes endpoint should be open, no authentication required
2. Currently. when downloading the result of a batch job, it requires again the authentication, it shouldn't be the case, probably it should use an already available token? (GET request to something like /download/JOB-ID/result.tiff)

**Comment by pierocampa** [comment]
> @pierocampa the code is still trying to connect to the Eurac authentication server despite the basic auth configuration is activated.

Ok, the problem is Spring Boot OAuth2 client autoconfiguration which is triggered even though the security component is disabled. Working on it today

**Comment by pierocampa** [comment]
> @pierocampa some things that need to be fixed before moving on:
> 
> 1. The /processes endpoint should be open, no authentication required

-> ef57d34

> 2. Currently. when downloading the result of a batch job, it requires again the authentication, it shouldn't be the case, probably it should use an already available token? (GET request to something like /download/JOB-ID/result.tiff)

This hence probably happened on expired authentication token, right?

**Comment by pierocampa** [comment]
> > @pierocampa the code is still trying to connect to the Eurac authentication server despite the basic auth configuration is activated.
> 
> Ok, the problem is Spring Boot OAuth2 client autoconfiguration which is triggered even though the security component is disabled. Working on it today

Ok, this should be fixed now also:  367aaa1

**Comment by pierocampa** [comment]
If you don't have time for a countercheck, we can proceed to merge the branch, then in case of further problems, we work on bugfixes. Here I ran all tests, they're good.

**Comment by clausmichele** [comment]
> > @pierocampa some things that need to be fixed before moving on:
> > 
> > 1. The /processes endpoint should be open, no authentication required
> 
> -> [ef57d34](https://github.com/Open-EO/openeo-spring-driver/commit/ef57d34ea13f1f4b222bebad4b4415d8fb8d45c7)
> 
> > 2. Currently. when downloading the result of a batch job, it requires again the authentication, it shouldn't be the case, probably it should use an already available token? (GET request to something like /download/JOB-ID/result.tiff)
> 
> This hence probably happened on expired authentication token, right?

Yes, probably it was due to the token! Yes, please proceed with the merge, I won't have time until Friday.

**Pull request merged**
