### PR TITLE
Feature arbitrary mdarrays

### PR DESCRIPTION
**Pull request by pierocampa**
This pull request includes the following enhancements, all involving the rasdaman/WCPS backend:

1. proper parsing of compound CRS from input WCS catalogue, with creation of arbitrary dimensions on non-EPSG and non-temporal (heuristic, the latter) axes
2. labels of the marshalled collection are taken from the GML coverage descriptions
3. axis type (that is, whether X or Y type) is derived from EPSG orientation attribute, for spatial axes
4. richer metadata is parsed from WCS description and marshalled
5. add missing STAC extensions + to be properly cited with URLs
6. loading of catalogues factored out onto a separate package `org.openeo.spring.api.loaders`
7. loading of catalogue, either online or from local cache, is parallelizable both inter- and (only for the WCS backend) intra-catalogue, through application property
8. decouple the loading of the two ODC/WCS backends
9. the server to accept process graph drafts with unidentifiable engine
10. Unit tests for the WCS loader

### CODE REVIEW

**Comment by pierocampa** [comment]
@aljacob / @clausmichele : any update/comment on this?

**Comment by clausmichele** [comment]
Thanks Piero! The parametrization seems fine, I just need to test if all the functionalities that I use works fine with this branch, using some sample jobs. Unfortunately, I won't have time until next Friday.

**Comment by pierocampa** [comment]
Thanks Michele! Do you mean tomorrow-Friday, or next week?
Anyway, let me know the outcome and if there's anything to correct before merging. !

**Comment by clausmichele** [comment]
@pierocampa after adapting the application.properties file and starting the driver I get this error which could be probably due to my GDAL version:
`java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: 'int org.gdal.osr.osrJNI.SpatialReference_ExportToPROJJSON__SWIG_1(long, org.gdal.osr.SpatialReference, java.lang.String[])'`

Due to this error, it doesn't load the available collection (none displayed under openeo_endpoint/collection) and I can't test it with some process graphs.

**Comment by pierocampa** [comment]
> SpatialReference_ExportToPROJJSON__SWIG_1

Yes, the GDAL libraries are not in the path or there is a mismatch in install/expected GDAL versions.
https://gitlab.inf.unibz.it/REMSEN/openeo-spring-driver-setup#javalangunsatisfiedlinkerror-no-gdalalljni-in-javalibrarypath

We can look into this together tomorrow or wed. !

**Comment by pierocampa** [comment]
Rebasing branch and creating a new PR (updating the branch did not resync this one)

**Pull request closed without merging**
